# -*- coding: utf-8 -*-
"""AMSAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZbFWZ07WCMDD4ujD2nfyifP70LYm8hI
"""

# AMSAT Rotation Analysis Pipeline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, fftfreq

# 1️ Load the data

df = pd.read_csv(
    "/content/resampled.txt",
    names=["timestamp", "face", "voltage", "current"],
    parse_dates=["timestamp"],
    dtype={"face": str, "voltage": float, "current": float},
    skipinitialspace=True
)

# Convert timestamp to seconds
t0 = df["timestamp"].iloc[0]
df["time_sec"] = (df["timestamp"] - t0).dt.total_seconds()


# 2️ Helper function for FFT analysis

def analyze_panel(df_panel, panel_name):
    time = df_panel["time_sec"].values
    voltage = df_panel["voltage"].values

    # Detrend
    voltage_detrended = voltage - np.mean(voltage)

    # FFT
    N = len(time)
    dt = np.mean(np.diff(time))
    freqs = fftfreq(N, dt)
    fft_values = fft(voltage_detrended)
    power = np.abs(fft_values)**2

    # Positive frequencies only
    mask = freqs > 0
    freqs_pos = freqs[mask]
    power_pos = power[mask]

    # Dominant frequency and angular rotation rate
    dominant_freq = freqs_pos[np.argmax(power_pos)]
    angular_rate = 2 * np.pi * dominant_freq

    # Plot voltage vs time
    plt.figure(figsize=(8,3))
    plt.plot(time, voltage, marker='.', linestyle='-')
    plt.xlabel("Time [s]")
    plt.ylabel("Voltage [V]")
    plt.title(f"{panel_name} Panel Voltage vs Time")
    plt.grid(True)
    plt.show()

    # Plot power spectrum
    plt.figure(figsize=(8,3))
    plt.plot(freqs_pos, power_pos)
    plt.xlabel("Frequency [Hz]")
    plt.ylabel("Power")
    plt.title(f"{panel_name} Panel FFT Power Spectrum")
    plt.grid(True)
    plt.show()

    print(f"{panel_name} Panel:")
    print(f"  Dominant frequency: {dominant_freq:.4f} Hz")
    print(f"  Angular rotation rate: {angular_rate:.4f} rad/s")
    print("-"*40)

    return dominant_freq, angular_rate

panels = ["+Y", "-Y"]
results = {}

for panel in panels:
    df_panel = df[df["face"] == panel].copy()
    if len(df_panel) > 0:
        freq, omega = analyze_panel(df_panel, panel)
        results[panel] = {"frequency": freq, "angular_rate": omega}

from google.colab import drive
drive.mount('/content/drive')

import re
import numpy as np
import matplotlib.pyplot as plt

# 1. SIMPLE DATA LOADING

filename = '/content/AccvsTime (1).txt'

# Storage lists
ax_list, ay_list, az_list = [], [], []
gx_list, gy_list, gz_list = [], [], []
panel_angle_list = []
time_list = []

t = 0   # time grows by each reading (approx)
dt = 2  # seconds between samples (from your logs)

with open(filename, "r") as f:
    for line in f:
        if "MPU6050" in line:

            nums = re.findall(r"[-+]?\d*\.\d+|\d+", line)
            # nums = [ax, ay, az, gx, gy, gz, XS_angle, XS_extra]

            if len(nums) >= 8:
                ax = float(nums[0])
                ay = float(nums[1])
                az = float(nums[2])
                gx = float(nums[3])
                gy = float(nums[4])
                gz = float(nums[5])
                xs = float(nums[6])  # solar panel angle

                ax_list.append(ax)
                ay_list.append(ay)
                az_list.append(az)
                gx_list.append(gx)
                gy_list.append(gy)
                gz_list.append(gz)
                panel_angle_list.append(xs)

                time_list.append(t)
                t += dt

# Convert lists to numpy arrays
t = np.array(time_list)
ax = np.array(ax_list)
ay = np.array(ay_list)
az = np.array(az_list)
gx = np.array(gx_list)
gy = np.array(gy_list)
gz = np.array(gz_list)
panel = np.array(panel_angle_list)

# 2. ANGULAR ACCEL FROM IMU

# Gyro is in deg/s → convert to rad/s
gyro_x = gx * np.pi/180

# numerical derivative
alpha_imu = np.gradient(gyro_x, dt)

# 3. ANGULAR ACCEL FROM PANEL

panel_rad = panel * np.pi/180
omega_panel = np.gradient(panel_rad, dt)
alpha_panel = np.gradient(omega_panel, dt)

# 4. PLOT BOTH

plt.figure(figsize=(10,5))
plt.plot(t, alpha_imu, label="Angular Accel (IMU)", linewidth=2)
plt.plot(t, alpha_panel, label="Angular Accel (Solar Panel)", linewidth=2)
plt.xlabel("Time (s)")
plt.ylabel("Angular acceleration (rad/s²)")
plt.legend()
plt.grid()
plt.title("Comparison of Angular Acceleration: IMU vs Solar Panel")
plt.show()

print(alpha_imu)